---
- name: Verify that the system is supported
  ansible.builtin.fail:
    msg: "The ansible-role-wordpress role only supports Debian/Ubuntu and RedHat/Rocky."
  when: ansible_os_family not in ["Debian", "RedHat"]

- name: Install prerequisites
  ansible.builtin.include_tasks: install.yml

- name: Configure MariaDB
  ansible.builtin.include_tasks: mariadb.yml

- name: Install WordPress
  ansible.builtin.include_tasks: wordpress.yml

- name: Configure Apache
  ansible.builtin.include_tasks: apache.yml

